
data_pipeline:
  data:
    input_dir: "data"
    output_dir: "data"

training:
  data: 
    input_dir: "data"
  config:    
    output_dir: "./model_output"
    parameter: 3
  artifacts:
    output_path: "./mlflow_artifacts"
  experiment_name : "my_databricks_project"
  model:
    model_name: "random_forest_model"
    n_estimators: 100
    max_depth: 5
    random_state: 42

mlflow_location: "databricks" # either "local" or "databricks"
