name: CICD Workflow

on:
  push:
    branches:
      - main
      - 'feature/**'  # Runs build job on any feature/* branch push
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'databricks.yml'
      - 'resources/*.yml'
      - 'requirements*'
      - 'setup.py'      
  pull_request:
    branches:
      - main  # Runs build, test, and deploy jobs on pull request to main branch

env:
  MAJOR_VERSION: 1
  MINOR_VERSION: 0
  # FEATURE_NAME: 'databricks-dab-demo'
  # OUTPUT_FOLDER: 'databricks-dab-demo'
  # CONDA_ENV_NAME: 'databricks-dab-demo'

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: development  # Use dev environment for build and validation
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies & check quality
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          # Uncomment the following lines if you want to run quality checks
          # make quality-ci
          # mypy .
          # pylint src/language_model_training

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version

      - name: Validate bundle
        env:
          # Note the host is an "environment variable" in the Github Environment
          # while the token is a "secret" in the Github Environment
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}      
        # run: make validate-bundle  
        run: databricks bundle deploy -t dev        

  # test:
  #   if: github.event_name == 'pull_request'
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: development
  #   steps:
  #     - name: Run Tests
  #       run: echo "Running tests..."

  # deploy-dev:
  #   if: github.event_name == 'pull_request'
  #   needs: test
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: development
  #   steps:
  #     - name: Deploy
  #       run: echo "Deploying..."

  deploy-production:
    if: github.event_name == 'pull_request'
    needs: build #deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: production
      # Requires approval for 'production' environment
    steps:
      - name: Deploy
        run: echo "Deploying..."  
        
      - name: Deploy bundle to dev
        env:
          # Note the host is an "environment variable" in the Github Environment
          # while the token is a "secret" in the Github Environment
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}      
        run: make deploy-bundle  
       
